### ISSUE TITLE
Contributors guidelines and project usage

### ISSUE THREAD

**Issue by vkresch** [OpenSimulationInterface/osi-validation#12]
A contributors guideline should exist so that new developers can implement new features or rules on their own. To make understanding inner workings of the project easier for new users there should be a step by step guide how to correctly validate a osi-message and what can go wrong. Also there should be a best practice reference how to debug the project.

This guideline needs to be a part of a centralized documentation for osi-validation.  Furthermore there needs to be a detailed guideline for defining releases and version numbers for the project.

**Comment by jdsika** [comment]
These guidelines should apply globally for the organization. We have to find a nice spot in order for everyone to see them.

**Comment by vkresch** [comment]
Sure I'm currently working on a prototype documentation for the **whole** OSI project based on sphinx which will have subtopics to the osi-validation, osi-visualizer, how to contribute to the project in general and documentation for the different releases.

**Comment by vkresch** [comment]
[Here](https://vkresch.github.io/osi-documentation/index.html) is the first version of the documentation (in the future the [repo](https://github.com/vkresch/osi-documentation) will be included in the osi organization). It consists of almost all the documentation from the OSI organization. There is also a [contributor's guide](https://vkresch.github.io/osi-documentation/osi/howtocontribute.html) which is inspired by the git workflow from our [wiki](https://github.com/OpenSimulationInterface/open-simulation-interface/wiki/Workflow) and from the [tezos project](http://tezos.gitlab.io/master/developer/contributing.html?highlight=contribution).

My next idea would be creating a topic in the documentation about the releases for OSI to document the changes and future work. There is also an interesting project called [breath](https://breathe.readthedocs.io/en/latest/) which enables to add doxygen xml files into sphinx so that we will have only one place for documentation and reference.

**Comment by jdsika** [comment]
Pretty cool!

**Comment by jdsika** [comment]
@engelben I would like you to have a DEEP look at this because I think this is the basis for the overall contribution guidelines we will have for the ASAM projects. Your feedback would be very much welcomed!

**Comment by jdsika** [comment]
@vkresch let us talk about "breath" in person and put that on the agenda for our next meeting!

**Comment by vkresch** [comment]
Change notes:
- updated [Contributor's Guideline](https://vkresch.github.io/osi-documentation/osi/howtocontribute.html)
- added [Commenting on fields with rules]( https://vkresch.github.io/osi-documentation/osi/commenting.html#commenting-on-fields-with-rules)
- added [Release topic]( https://vkresch.github.io/osi-documentation/osi/releases.html )
- added linux [setup guide](https://vkresch.github.io/osi-documentation/osi-validator/setup.html) for osi-validation
- added [usage guide](https://vkresch.github.io/osi-documentation/osi-validator/usage.html) for osi-validation

**Comment by jdsika** [comment]
Dynamic Duncan 🥇  Did you parse the information or did you copy it manually? If we keep the name we have to update the release titels

**Comment by vkresch** [comment]
For now I copied it manually but it in the future if required it can be easily parsed

**Comment by jdsika** [comment]
A proper centralized documentation with a proper auto build pipeline and valid information is the highest priority.

**Comment by jdsika** [comment]
I am a bit confused by the fact that the contributors guidelines exist multiple times?
