### ISSUE TITLE
Deploy Github Pages

### ISSUE THREAD

**Issue by ainar** [OpenSimulationInterface/osi-validation#3]
I deployed the documentation on my github pages at https://ainar.github.io/osi-validation/documentation/

The branch "gh-pages" need to be created to be able to merge it.

**Comment by CezarySzyszkaAltran** [comment]
Created.

**Comment by ainar** [comment]
The PR to deploy the documentation: https://github.com/OpenSimulationInterface/osi-validation/pull/4

**Comment by ainar** [comment]
Is it possible to activate the Github pages by selecting this in the Settings tab please?

![image](https://user-images.githubusercontent.com/12114853/54602533-3c364f80-4a42-11e9-9d8e-54dbf477418f.png)

**Comment by CarloVanDriestenBMW** [comment]
Sorry for not watching the issues here! I am all yours now!

**Comment by CarloVanDriestenBMW** [comment]
![grafik](https://user-images.githubusercontent.com/25304009/55537065-9fb7b280-56bb-11e9-8e63-02a3b6ce16e3.png)

**Comment by ainar** [comment]
> ![grafik](https://user-images.githubusercontent.com/25304009/55537065-9fb7b280-56bb-11e9-8e63-02a3b6ce16e3.png)

Hey! Everything is normal, I keep some space at the root for the documentation of the validator.

However the KPIs documentation can be found there thanks to you: https://opensimulationinterface.github.io/osi-validation/KPIs/

**Comment by ainar** [comment]
I need to be able to push into gh-pages to update the documentation.

**Comment by pmai** [comment]
Added new validation lead developer team, which is allowed (along with CCB) to push to gh-pages (and also allowed to push to other branches, with the usual PR-requirement for master).

**Comment by jdsika** [comment]
@vkresch I think this can be closed.
