### ISSUE TITLE
Error during validation run

### ISSUE THREAD

**Issue by ClemensLinnhoff** [OpenSimulationInterface/osi-validation#45]
#### Describe the bug
When trying to validate my own trace file (the example trace does not work, see #44), I get the following error:
```
File "osi-validation/venv/lib/python3.10/site-packages/osivalidator/osi_trace.py", line 330, in get_messages_in_index_range
    message.ParseFromString(serialized_message)
google.protobuf.message.DecodeError: Error parsing message
sys:1: ResourceWarning: unclosed file <_io.BufferedReader name='data/20230508T145835Z_sd_350_300_0000.osi'>
```

The trace file itself seems to be okay, since at least the OSI visualizer can load and display the data. It says "unclosed file", so maybe its a problem that I opened the file with the visualizer first? I don't know.

#### Describe how to reproduce the bug
1. generate rules with `rules2yml.py`
2. Run `osivalidator data/20230508T145835Z_sd_350_300_0000.osi --rules rules --type SensorData`

#### Describe the OS you are using
 - OS: Ubuntu 22.04

**Comment by vkresch** [comment]
@ClemensLinnhoff could you share your/a trace file to reproduce the issue?
