### ISSUE TITLE
Update README.md(s)

### ISSUE THREAD

**Issue by ainar** [OpenSimulationInterface/osi-validation#6]
Write some documentation on the validation program, how to install and how to use it in the README.md of the root of the repository.

Same for the KPIs and the deployment of the Doxygen documentation.

**Comment by jdsika** [comment]
This should be solved in conjunction with #12

**Comment by jdsika** [comment]
* build passing
* header "Short instructions"
* link to central documentation

**Comment by jdsika** [comment]
This is done. Good job!
